export enum SubModulosAgenda {
    AGENDA = "AGENDA",
    CLIENTES = "CLIENTES",
    PROFISSIONAIS = "PROFISSIONAIS",
    PESSOAS = "PESSOAS",
    USUARIOS = "USUARIOS",
    HISTORICO = "HISTORICO",
    MENSAGEM = "MENSAGEM",
    CAIXA = "CAIXA"
}

